### add a trade
POST http://localhost:3000/api/trade/addTrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
    "walletID": "61ff6860f34e24bd35827c95",
    "tradeGroup": "somethingelse",
    "tradeDescription": "description here !!!",
    "amount": -1500,
    "type": "spend",
    "date": "31-01-2021",
    "walletInclude": true
}

### update a trade
POST http://localhost:3000/api/trade/updateTrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
    "walletID": "61ff6860f34e24bd35827c95",
    "tradeID": "61ff6b69f34e24bd35827cb8",
    "newTradeGroup": "somethingelse",
    "newTradeDescription": "des: shopping updated",
    "newAmount": -6000,
    "newType": "spend",
    "newDate": "31-05-2021",
    "newWalletInclude": true
}

### delete a trade
DELETE http://localhost:3000/api/trade/deleteTrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDQxMjYyNDF9.fIwV9QTpGV6ELQW4ucO7MMIkq3OWNJKiNe9zale293A

{
    "walletID": "61ff6860f34e24bd35827c95",
    "tradeID": "61ff6b69f34e24bd35827cb8"
}

### delete multiple trades
DELETE http://localhost:3000/api/trade/deleteManyTrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
    "walletID": "61e2888d2d154b75779db913",
    "tradeIDList": ["61ff6b69f34e24bd35827cb8", "61e288f12d154b75779db91d"]
}

### get a trade
GET http://localhost:3000/api/trade/getTrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
    "walletID": "61ff6860f34e24bd35827c95",
    "tradeID": "61ff6b69f34e24bd35827cb8"
}

### get all trades
GET http://localhost:3000/api/trade/getAllTrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
    "walletID": "61ff6860f34e24bd35827c95"
}

### get trades by year
GET http://localhost:3000/api/trade/getTradesByYear
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDQxMjYyNDF9.fIwV9QTpGV6ELQW4ucO7MMIkq3OWNJKiNe9zale293A

{
    "walletID": "61ff6860f34e24bd35827c95",
    "year": 2022
}