POST http://localhost:3000/api/wallet/createNewWallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDQxMjYyNDF9.fIwV9QTpGV6ELQW4ucO7MMIkq3OWNJKiNe9zale293A

{
  "walletName": "[lam] wallet 22222",
  "walletDescription": "dffdgftyhn rtysbger yerysert agvter fgerfg ergerg er",
  "walletBalance": 150000,
  "totalInclude": true
}

### get wallet
POST http://localhost:3000/api/wallet/getWallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDQwNjkyNzF9.nXz955Ke1a7aC35Eq47CTEqhDMd9IRKLx4w9Z9oROvU

{
  "walletID": "61e2888d2d154b75779db913"
}

### get wallet by User
GET http://localhost:3000/api/wallet/getWalletByUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWRkOGI4YjA0ZDQyODA0YmRlODgzOWIiLCJpYXQiOjE2NDIwNDEyNTh9.VLKY4qrk6GhzT1g5BWPmtH5-uncI8cxbPrLNNcibwXc

### update wallet
POST http://localhost:3000/api/wallet/updateWallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
  "walletID": "61ff6860f34e24bd35827c95",
  "newWalletName": "[lam] wallet 1 updated",
  "newWalletDescription": "description of wallet 1 updated",
  "newWalletBalance": 118000,
  "newTotalInclude": false
}


### delete wallet
DELETE http://localhost:3000/api/wallet/deleteWallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MWUyMmU3ZGY5ODUxZGVhZTMzNzEyM2UiLCJpYXQiOjE2NDIyMzIwMTF9.R3SEfAFwKfPCWhYNlPOD84gQbs1C0LJzrce0ECbAIUc

{
  "walletID": "61e2795527eb88dbe78b6d34"
}
